---
- name: Test Vault plugin
  hosts: localhost
  tasks:
    - name: Test Vault lookup
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'my_secret/data/credentials') }}"
