---
- name: SSH into host and run pwd command
  hosts: ubuntu
  gather_facts: no
  tasks:
    - name: Run pwd command
      command: pwd
      register: result

    - name: Display the output of pwd
      debug:
        msg: "The current working directory is: {{ result.stdout }}"
