---
- name: Use credentials from inventory for password on Ubuntu machines
  hosts: ubuntu
  gather_facts: no

  tasks:
    - name: Display the password (or use it in other tasks)
      ansible.builtin.debug:
        msg: "The SSH password from the inventory is {{ ansible_ssh_pass }}"
