- name: Use hardcoded credentials to connect to 11.0.0.150
  hosts: 11.0.0.150
  gather_facts: no
  tasks:
    - name: Display SSH credentials
      ansible.builtin.debug:
        msg: "Using SSH with username {{ ssh_user }} and password {{ ssh_password }}"

    - name: Run a simple command
      ansible.builtin.command:
        cmd: pwd
      become: yes
      become_method: sudo
      vars:
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_pass: "{{ ssh_password }}"
      become_password: "{{ sudo_password }}"  # Provide sudo password here

  vars:
    ssh_user: "vinish"
    ssh_password: "ICICI1@src"
    sudo_password: "ICICI1@src"  # Replace with the sudo password for the user
