---
- name: Prompt for password on Ubuntu machines
  hosts: ubuntu
  gather_facts: no

  tasks:
    - name: Prompt for password input
      ansible.builtin.shell: echo "Your password is {{ password }}"
      vars_prompt:
        - name: password
          prompt: "Enter the password"
          private: yes
