- name: Use AWX credentials to connect to 11.0.0.150
  hosts: all
  gather_facts: no
  tasks:
    - name: Retrieve SSH credentials from HashiCorp Vault
      community.hashi_vault.hashivault_read:
        secret: "secret/credential"
      register: vault_data

    - name: Debug Vault JSON response
      debug:
        var: vault_data  # Prints the entire JSON response from Vault

    - name: Extract SSH user and password from Vault
      set_fact:
        ssh_user: "{{ vault_data.data.keys() | first }}"  # Extract the key name (e.g., 'vinish')
        ssh_password: "{{ vault_data.data[ssh_user] }}"   # Extract the value (e.g., the password)

    - name: Debug SSH user
      debug:
        msg: "SSH User: {{ ssh_user }}"

    - name: Debug SSH password
      debug:
        msg: "SSH Password: {{ ssh_password }}"

    - name: Run a simple command (e.g., pwd)
      ansible.builtin.command:
        cmd: pwd
      vars:
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_pass: "{{ ssh_password }}"
      register: pwd_result

    - name: Display the pwd command output
      debug:
        msg: "The output of the command is: {{ pwd_result.stdout }}"
