- name: Use AWX credentials to connect to 11.0.0.150
  hosts: ubuntu
  gather_facts: no
  vars:
    vault_addr: "http://11.0.0.1:8080"  # Define the Vault URL
    vault_token: "root"     # Vault token if required
  tasks:
    - name: Retrieve SSH credentials from HashiCorp Vault
      community.hashi_vault.hashivault_read:
        secret: "secret/credentials"
        url: "{{ vault_addr }}"           # Pass the Vault URL
        token: "{{ vault_token }}"         # Pass the Vault token (if required)
      register: vault_data
