- name: Retrieve SSH credentials from HashiCorp Vault using community.hashi_vault.vault_kv2_get
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get SSH credentials from Vault
      community.hashi_vault.vault_kv2_get:
        url: "http://11.0.0.1:8080"  # Optional if Vault URL is already in the credential
        path: "credentials"  # The correct path to your secret
      register: vault_response

    - name: Debug Vault response
      debug:
        var: vault_response

    - name: Extract SSH user and password from Vault response
      set_fact:
        ssh_user: "{{ vault_response.data.data.ssh_user }}"  # Correct path to the username in the response
        ssh_password: "{{ vault_response.data.data.ssh_password }}"  # Correct path to the password in the response

    - name: Debug SSH user
      debug:
        msg: "SSH User: {{ ssh_user }}"

    - name: Debug SSH password
      debug:
        msg: "SSH Password: {{ ssh_password }}"

    - name: Display SSH credentials
      ansible.builtin.debug:
        msg: "Using SSH with username {{ ssh_user }} and password {{ ssh_password }}"

    - name: Run a simple command (e.g., hostname)
      ansible.builtin.command:
        cmd: hostname
      become: yes
      become_method: sudo
      become_user: root
      vars:
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_pass: "{{ ssh_password }}"
        ansible_become_password: "{{ sudo_password }}"
      register: hostname_result

    - name: Display the hostname command output
      ansible.builtin.debug:
        msg: "The output of the hostname command is: {{ hostname_result.stdout }}"
