- name: Use AWX credentials to connect to 11.0.0.150
  hosts: all
  gather_facts: no
  tasks:
    - name: Display SSH credentials
      ansible.builtin.debug:
        msg: "Using SSH with username {{ ansible_user }} and password {{ ansible_ssh_pass }}"

    - name: Run a simple command (e.g., pwd)
      ansible.builtin.command:
        cmd: pwd
      register: pwd_result

    - name: Display the pwd command output
      ansible.builtin.debug:
        msg: "The output of the command is: {{ pwd_result.stdout }}"
