- name: Retrieve SSH credentials from HashiCorp Vault using ansible.builtin.uri
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get SSH credentials from Vault
      ansible.builtin.uri:
        url: "http://11.0.0.1:8080/v1/secret/data/credentials"  # Replace with your Vault URL and secret path
        method: GET
        headers:
          X-Vault-Token: "root"  # Hardcoded Vault token
        validate_certs: no  # Set to 'yes' if using a valid SSL certificate
        return_content: yes
      register: vault_response

    - name: Debug Vault response
      debug:
        var: vault_response

    - name: Extract SSH user and password from Vault response
      set_fact:
        ssh_user: "{{ vault_response.json.data.data.ssh_user }}"  # Adjust based on the key names in your Vault data
        ssh_password: "{{ vault_response.json.data.data.ssh_password }}"  # Adjust based on the key names in your Vault data

    - name: Debug SSH user
      debug:
        msg: "SSH User: {{ ssh_user }}"

    - name: Debug SSH password
      debug:
        msg: "SSH Password: {{ ssh_password }}"

    - name: Run a simple command using SSH credentials
      ansible.builtin.command:
        cmd: pwd
      vars:
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_pass: "{{ ssh_password }}"
      register: pwd_result

    - name: Display the pwd command output
      debug:
        msg: "The output of the command is: {{ pwd_result.stdout }}"
